### ISSUE TITLE
REVERT version

### ISSUE THREAD

**Issue by 0A7V9A** [Jisll/windows11#1]
Hi!
Can you please make a revert version ?
Now cant even install NetFramewrok 3.5 from Windows Features (0x800F0922).

**Comment by vacpp** [comment]
The issue you’re experiencing might be related to Windows Update. Therefore, you should navigate to the Services and look for Windows Update. Make sure it’s turned on and set to Automatic. After doing this, you should be able to install it again. They merely disable unnecessary services and make minimal, safe changes to the registry. So it should be fine.
